---

- name: Copy config file
  copy:
    content: "{{ lookup('file', config_file_path) }}"
    dest: /tmp/portchecker.config

- include_tasks: apiserver.yml
  when: portchecker_run_mode == 'apiserver'

- include_tasks: agent.yml
  when: |
    portchecker_run_mode == 'check-agent' ||
    portchecker_run_mode == 'probe-agent'

...
